set --global CMDFILE_COMPLETIONS_PATH (realpath (dirname (status --current-filename))/../completions)
set --global CMDFILE_CONFD_PATH (realpath (dirname (status --current-filename)))
set --global CMDFILE_FUNCTIONS_PATH (realpath (dirname (status --current-filename))/../functions)
set --global CMDFILE_MANUALS_PATH (realpath (dirname (status --current-filename))/../manuals)
set --global CMDFILE_PATH (realpath (dirname (status --current-filename))../)
set --global CMDFILE_THEMES_PATH (realpath (dirname (status --current-filename))/../themes)
